Revert "Use minimal partitioning"
This reverts commit 27fec7a7b462e6f96451187f2306d50ec30d53a8.

Because it causes the following error:

[7f5eab155740] (manager) Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/nailgun/task/manager.py", line 51, in _call_silently
    return method(task, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/nailgun/task/task.py", line 569, in execute
    cls._check_disks(task)
  File "/usr/lib/python2.6/site-packages/nailgun/task/task.py", line 626, in _check_disks
    node.volume_manager.check_disk_space_for_deployment()
  File "/usr/lib/python2.6/site-packages/nailgun/db/sqlalchemy/models/node.py", line 145, in volume_manager
    return VolumeManager(self)
  File "/usr/lib/python2.6/site-packages/nailgun/volumes/manager.py", line 587, in __init__
    self.allowed_volumes = get_node_spaces(node)
  File "/usr/lib/python2.6/site-packages/nailgun/volumes/manager.py", line 131, in get_node_spaces
    space = find_space_by_id(all_spaces, volume['id'])
  File "/usr/lib/python2.6/site-packages/nailgun/volumes/manager.py", line 70, in find_space_by_id
    return filter(lambda space: space.get('id') == space_id, spaces)[0]
IndexError: list index out of range